### ISSUE TITLE
代码默认展开

### ISSUE THREAD

**Issue by Akimio521** [wleelw/hexo-theme-solitude#106]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

代码默认展开这里，选择true反而没有展开
![daa06dc80a2ba38a584e13276e6c8e74](https://github.com/wleelw/hexo-theme-solitude/assets/77880495/1ef8759f-7a4b-43ec-8f7a-6811e8b650fe)
![fa31631c66bfba32a5f90a12e993b26a](https://github.com/wleelw/hexo-theme-solitude/assets/77880495/a03d8624-95ff-4a44-9fca-27d54d88860e)

### 终端日志 📒

<此处粘贴终端日志>

**Comment by wleelw** [comment]
dev 已修复
