### ISSUE TITLE
主题色识别失败

### ISSUE THREAD

**Issue by Akimio521** [wleelw/hexo-theme-solitude#107]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

主题色识别失败，无论是local还是api
实测png图片正常，但是webp图片识别失败
![dd2dc0aad718db759bc84d74cf37d83e](https://github.com/wleelw/hexo-theme-solitude/assets/77880495/ee893c55-b7cf-4fbb-9e2a-f5878c2c27b8)
![e1f7d6f813dd47d1dfefdbc58db461eb](https://github.com/wleelw/hexo-theme-solitude/assets/77880495/2e9ca453-3f48-4cdb-b1c9-e718a4e94dcf)
图床的存储服务是CloudFlare R2存储服务（类s3）

### 终端日志 📒

<此处粘贴终端日志>

**Comment by yife68** [comment]
你好，我是Solitude主题取色功能的开发者，亦小封。麻烦提供下你的webp图片链接。

**Comment by Akimio521** [comment]
> 你好，我是Solitude主题取色功能的开发者，亦小封。麻烦提供下你的webp图片链接。

https://img.akimio.top/Blog/2024/01/1705725058-65ab4c824e8bd.webp

**Comment by wleelw** [comment]
api 项目地址：https://github.com/anzhiyu-c/img2color-go
有图片拾取报错提issue

**Comment by wleelw** [comment]
> api 项目地址：https://github.com/anzhiyu-c/img2color-go 有图片拾取报错提issue

<img width="969" alt="image" src="https://github.com/wleelw/hexo-theme-solitude/assets/74389842/8154415e-d9ab-4d1f-ac54-9ed30375cccc">

**Comment by wleelw** [comment]
我开发了一个使用 vercel KV 做缓存的项目，可以试试
https://github.com/wleelw/img2color
