### ISSUE TITLE
想对开发者说

### ISSUE THREAD

**Issue by RicharPao** [wleelw/hexo-theme-solitude#110]
### 想要的功能 | What feature do you want?

Solitude也是Hexo中又一个Heo风格的主题，我个人也是非常喜欢Heo的设计，真的希望王哥能够坚持维护下去，还原程度这么高也很不容易，别像隔壁亚克力一样都停更了(bushi

**Comment by wleelw** [comment]
主题不会停更，我会在学业之余进行维护，有什么问题都可以提
