### ISSUE TITLE
[Feature]: 希望能新增瀑布流相册功能

### ISSUE THREAD

**Issue by hulebaji** [wleelw/hexo-theme-solitude#111]
### 想要的功能 | What feature do you want?

希望能新增瀑布流相册功能

**Comment by wleelw** [comment]
done [commit](https://github.com/wleelw/hexo-theme-solitude/commit/f7a40034ba058bc57a49716352d25582dc38be52)

**Comment by wleelw** [comment]
https://blog.wzsco.top/gallery/
预览
