### ISSUE TITLE
[Feature]:  添加Fancybox灯箱

### ISSUE THREAD

**Issue by RicharPao** [wleelw/hexo-theme-solitude#114]
### 想要的功能 | What feature do you want?

虽然现在的Lightbox很好，但是只能实现基本的zoom功能
可以试试更强大的Fancybox灯箱，功能更加丰富
官方文档：https://fancyapps.com/fancybox/
文档中提供了一些可选配置，比如：是否显示底部的缩略图，图片的切换动画等等（自己试试就知道了）
也是非常的不错，希望可以添加进来并结合Solitude设计风格进行美化 :)

**Comment by wleelw** [comment]
Fancybox 需要使用JQuery且无法替代，主题本着万物皆原生的理念

**Comment by wleelw** [comment]
done [commit](https://github.com/wleelw/hexo-theme-solitude/commit/9f480525098b79ef673a28e99c880602c7aaccab)

**Comment by wleelw** [comment]
<img width="2264" alt="image" src="https://github.com/wleelw/hexo-theme-solitude/assets/74389842/3a8a1948-3f36-446a-a82f-b83bd7abb01d">

**Comment by wleelw** [comment]
已添加，自定义动画或是缩略图，有能力可以交pr，我最近比较忙
