### ISSUE TITLE
使用katex公式时会导致文章小标题靠右

### ISSUE THREAD

**Issue by CodyJWang** [wleelw/hexo-theme-solitude#116]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

![image](https://github.com/wleelw/hexo-theme-solitude/assets/96332125/48646071-0550-49c2-a1ca-c00d4c18c383)

### 终端日志 📒

<此处粘贴终端日志>

**Comment by wleelw** [comment]
使用 进阶版的 markdown渲染器请看作者博客介绍：[Solitude 数学公式](https://blog.wzsco.top/p/b1d1f75b.html)
