### ISSUE TITLE
[Feature]: 站外跳出提示页面

### ISSUE THREAD

**Issue by Akimio521** [wleelw/hexo-theme-solitude#120]
### 想要的功能 | What feature do you want?

可以参考一下下面的文章：
https://www.yichkhun.com/p/9b8131b0.html
同时希望可以美化一下，更符合整体样式

**Comment by yife68** [comment]
谢谢你的提议。但目前阶段暂无该功能开发的想法，后续如有需求会将此issues打开并实现。

**Comment by yife68** [comment]
在此之前，可自行进行魔改使用。
